# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chats

pod 'FirebaseCore'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'FirebaseAnalytics'
pod 'FirebaseMessaging'
pod 'FirebaseFirestoreSwift'

pod 'Gallery'
pod 'ProgressHUD'
pod 'MessageKit'
pod 'InputBarAccessoryView'

pod 'SnapKit', '~> 5.6.0'

end
